### ISSUE TITLE
[Task 01][ricardodalarme] Implement a header component for List Page

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#10]
On this task you will implement a simple header component that will have two buttons, an image and a text.

** Git Etiquette **

Since this will be your first time submitting a PR, please make sure to follow our git etiquette.

- Use conventional [commits](https://www.conventionalcommits.org/en/v1.0.0/) (we highly recommend to use the commit body to describe the changes, even if it is redundant):
- Don't submit a fix commit to something that was introduced in your PR. It's recommended to [rewrite your's PR commit history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) and squash the fix into that commit. Fix commits are for features that are already merged into the main branch.

**Tasks:**

- [ ] Create a header component, replacing the BaseHeader one.
- [ ] Put that component inside the `components/OnboardTask/<ComponentName>` folder.
- [ ] Add a hamburger menu icon on the left side of the app-bar.
- [ ] Add ProFusion logo at the center
- [ ] Add on the right side of the menu icon, the title of the route.
- [ ] Add a profile icon on the right side of the app-bar.

**Acceptance Criteria:**

- [ ] Use OnboardingTask in the component path to indicate this component was created because of your onboarding.
- [ ] Your component should be responsive 
- [ ] The text value should be used from INTL
- [ ] The color should be used from theme
- [ ] (Optional) Showcase your component in Storybook

**Layout Reference:**

https://www.figma.com/file/8sG5407vluhY4PTuoUW0Y4/Quickstart-React-pages?node-id=0%3A1
