### ISSUE TITLE
[Task 03][ricardodalarme] Implement a Drawer component for Header - Part 02

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#12]
On this task, you should finish enhancing the header creating another Drawer for the User informations.

**Tasks:**

- [ ] Create a user information drawer
- [ ] Create a query to get user's information
- [ ] The drawer should have the user's avatar, name, last name and email
- [ ] Add a Close Button at the Right Top of the Component
- [ ] Add a controller of the app theme at the end of the drawer as it is shown on figma.

**Acceptance Criteria:**

- [ ] Use OnboardingTask in the component path to indicate this component was created because of your onboarding.
- [ ] Your component should be responsive 
- [ ] The drawer must be open only if the Avatar Icon on Header is clicked
- [ ] The drawer must be closed if the Close Icon or outside of the drawer is clicked 
- [ ] You must use mui icons 
- [ ] (Optional) Showcase your component in Storybook

**Reference Image:**

https://www.figma.com/file/8sG5407vluhY4PTuoUW0Y4/Quickstart-React-pages?node-id=40%3A187
