### ISSUE TITLE
[Task 06][ricardodalarme] Adding Organization

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#15]
On this task you will learn more about mutations creating a new Organization.

**Tasks:**

- [ ] Create a button in Organizations route to open a modal after its click
- [ ] The modal should have a form and on the tags input, it should have a multiselector list of tags: tag0, tag1, tag2, ..., tag 10
- [ ] After confirming the data in the form, you should handle the error and success with the SnackBar.
- [ ] The modal must be closed when send the request

**Acceptance Criteria:**

- [ ] Use OnboardingTask in the component path to indicate this component was created because of your onboarding.
- [ ] Your component should be responsive 
- [ ] The placeholder values should be used from INTL
- [ ] The color should be used from theme
- [ ] Snackbar is shown after creating a new Organization or if it had an error
- [ ] The new Organization should be shown on the List if it is a success
- [ ] (Optional) Showcase your component in Storybook

**Reference Video:**

https://user-images.githubusercontent.com/73129958/170145173-1b83c689-5f82-43dc-9b5f-a1547e79e615.gif
