### ISSUE TITLE
[Task 04][ricardodalarme] Implement an Organization Page

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#21]
On this task you will implement another Route called Organization.

**Tasks:**

- [ ] Create a List of Organizations with mocked data
- [ ] Create two buttons for Edit and Remove for each organization at the end

**Acceptance Criteria:**

- [ ] Use OnboardingTask in the component path to indicate this component was created because of your onboarding.
- [ ] Your component should be responsive 
- [ ] The Name value should be used from INTL
- [ ] The color should be used from theme
- [ ] (Optional) Showcase your component in Storybook

**Reference Image:**

https://www.figma.com/file/8sG5407vluhY4PTuoUW0Y4/Quickstart-React-pages?node-id=0%3A1
