### ISSUE TITLE
[Task 05][ricardodalarme] Populate the Organization Page

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#22]
On this task you will populate the Organization Page with data from the backend using GraphQL.

**Tasks:**

- [ ] Create a query to get organizations data
- [ ] Use query data in your list of organizations instead of mocked data

**Acceptance Criteria:**

- [ ] Fetch only the first 5 Organizations

**Documentation:**

- [Creating a custom hook for queries and mutations](https://github.com/profusion/quickstart-react-graphql/blob/main/docs/creating_custom_hooks_for_queries_mutations.md)
