### ISSUE TITLE
[Task 02][wilson] Implement a Drawer component for Header - Part 01

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#3]
On this task, you should start enhancing the header and the navigation system.
Take a little time to pay attention to the following:
It's important to optimize your time so you can assure that you can meet the deadlines. For that reason, we are using a component library.
So before you start, always take a look at the official documentation to see if there is something there that you can use. If not, you can always start from scratch.

**Tasks:**

- [ ]  Create a navigation drawer component, that should be toggled via the hamburger menu icon(left side of the header that you created on Task 1).
- [ ]  Inside the drawer component, you should list all available routes (except login, forget password, dev menu) as ListItems. Clicking on a ListItem should drive you to the respective route.
- [ ]  Create a Logout button just below the routes. It should be separated by a Divider. Logout button should drive you to the login page.
- [ ]  Implement a logout handler and redirect the user to the Login page.

**Acceptance Criteria:**

- [ ] Use OnboardingTask in the component path to indicate this component was created because of your onboarding.
- [ ] Your component should be responsive 
- [ ] The text value should be used from INTL
- [ ] The color should be used from theme
- [ ] (Optional) Showcase your component in Storybook

**Reference Image:**

https://www.figma.com/file/8sG5407vluhY4PTuoUW0Y4/Quickstart-React-pages?node-id=0%3A1
