### ISSUE TITLE
[Task 05][wilson] Pagination and Search Organization Page

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#6]
On this task you will enhance your Organization route. Check out the custom hooks on the "hooks" or "services" folder to see if there is anything that you can use.

**Tasks:**

- [ ] The query is now paginated, adapt your code to handle it
- [ ] Add a Pagination on the bottom of the List using the pagination component that already exists
    - It must contain:
      - [ ] Go back (only after the first page)
      - [ ] Go First (only after the first page)
      - [ ] Go Forward (if not the last page)
      = [ ] Actual page / Number of pages
- [ ] Add a filter on the top right side of the list
    - When a value is added it must show a Clear Button, that on its click it will clear the input
    - When Search Button is clicked it must search for that organization
- [ ] Add a capture screen recording and add to the PR showcasing the functionality: it should contain:
    - [ ] One page change
    - [ ] Filtering an organization
    - [ ] Clear the filter

**Hint**

You don't need to re-trigger the query with the filter and with the pagination, your hook and apollo will handle it. Look for examples in the docs.

**Acceptance Criteria:**

- [ ] Use OnboardingTask in the component path to indicate this component was created because of your onboarding.
- [ ] Your component should be responsive 
- [ ] The Name value should be used from INTL
- [ ] The color should be used from theme
- [ ] Filter is working
- [ ] Pagination is working
- [ ] Clear filter is working
- [ ] Add a screen recoding of the component on the PR
- [ ] (Optional) Showcase your component in Storybook

**Reference Image:**

https://www.figma.com/file/8sG5407vluhY4PTuoUW0Y4/Quickstart-React-pages?node-id=0%3A1
