### ISSUE TITLE
[Task 07][wilson] Delete Organization

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#8]
On this task you will try another mutation to delete an Organization, it's recommended that you take a look at Apollo's built in functionality.

**Tasks:**

- [ ] Create a delete confirmation modal
- [ ] The modal should open if the Trash Icon on the Organization is clicked
- [ ] It should only remove the Organization if the confirmation button is clicked

**Acceptance Criteria:**

- [ ] Use OnboardingTask in the component path to indicate this component was created because of your onboarding.
- [ ] Your component should be responsive 
- [ ] The text value should be used from INTL
- [ ] The color should be used from theme
- [ ] It should show a Snackbar if it is a success or an error
= [ ] it should reflect on the List, if you only have one Organization, it should show a message that it doesn't exist Organizations. You should treat all cases.
- [ ] (Optional) Showcase your component in Storybook

**Reference Image:**

<img width="517" alt="Captura de Tela 2021-07-09 às 13 25 49" src="https://user-images.githubusercontent.com/29777650/150143382-1453e81b-ad22-4eb1-beae-b4c65fe718b6.png">

https://www.figma.com/file/8sG5407vluhY4PTuoUW0Y4/Quickstart-React-pages?node-id=0%3A1
