### ISSUE TITLE
[Task 00][ricardodalarme] Get ready to start

### ISSUE THREAD

**Issue by ricardodalarme** [ricardodalarme/env-test#9]
Hey there, welcome to the Onboarding, this is your first task.
During the entire onboarding process, feel free to ask for help if you need it, we will be glad to help you.

**Tasks:**

- [ ] Clone the repo
- [ ] Read documentation (both the `README.md` and the [quickstart-react-graphql/docs](https://github.com/profusion/quickstart-react-graphql/tree/main/docs), it's also recommended to read the official React Docs)
- [ ] Configure your environment (**yarn setup-env**)
- [ ] Checkout to your branch (onboarding-[your github's name]/main)
- [ ] Get used to the recommended IDE
- [ ] Install the dependencies (**yarn install**).
- [ ] Use the app for fist time (make sure you can log in).
- [ ] Take some time to get familiarized with the source code.
- [ ] **optional** The `yarn setup-env` already set the `.env` to point the backend to the the one hosted AWS, but if you want, you can change an option in the dev menu to use a local instance ([quickstart-graphql](https://github.com/profusion/quickstart-graphql)).

<img data-target="animated-image.replacedImage" alt="gif explaining how to use a local backend" class="AnimatedImagePlayer-animatedImage" src="https://user-images.githubusercontent.com/73129958/169388341-fde61847-ad0f-494a-9a01-10a469b37f47.gif" style="display: block; opacity: 1;">
